/**
 * Programmatic README generation for generated plugins.
 */
export default function generateReadme({
  name,
  shapes,
  surfaces,
  clientEnabled
}: {
  name: string
  shapes: string[]
  surfaces: string[]
  clientEnabled: boolean
}): string {
  const shapesLine = shapes.length === 0 ? 'hello (default)' : shapes.join(', ')
  const sections: string[] = []

  sections.push(`# ${name}

Generated by [create-dsh](https://www.npmjs.com/package/create-dsh).

## Selected shapes

- ${shapesLine}
`)

  if (shapes.includes('config')) {
    sections.push(`## Config & live settings

The config shape registers a Schemastery \`Config\` (greeting / maxRetries /
verbose) and wires it as a settings namespace via
\`installSettingsSection\`: the cordis.yml entry is the composition base
layer; every consumer reads through \`configSource()\`, so GUI edits take
effect immediately without a restart. The settings service being absent falls
back to the composition entry (identical behavior to no wiring at all).
`)
  }

  if (shapes.includes('commands')) {
    sections.push(`## Slash commands

\`/hello\` replies "world" through the default GenericCommandCard row;
\`/dsh-demo\` echoes its input${
      surfaces.includes('commandview')
        ? ' and renders through the custom commandview row (conversation.chat.commandview)'
        : ''
    }. Both register as optional sub-plugins (\`ctx.inject(['commands'])\`) and
silently skip when the commands service is not composed.
`)
  }

  if (shapes.includes('hook')) {
    sections.push(`## Permission gate

The hook half listens on \`tools/pre-execute\` and denies any tool listed in
its \`denyTools\` config (mounted from the commented-ready row in
cordis.patch.yml).
`)
  }

  if (clientEnabled) {
    const surfacesLine = surfaces.length === 0 ? 'none' : surfaces.join(', ')
    sections.push(`## Client half & UI surfaces

- Surfaces: ${surfacesLine}

\`pnpm dev\` rebuilds the browser bundle; with dsh-client-hmr active,
client changes hot-reload without restarting dsh web. Host changes still
require a dsh restart.
`)
  }

  sections.push(`## Development

\`pnpm install && pnpm build && pnpm check\` — format/lint/types via vp check, plus the smoke test.

Install into a profile with:

\`dsh plugin --profile web add link:$(pwd)\`
`)

  return sections.join('\n')
}
